config/routes.rb
Rails.application.routes.draw do
  root to: "top#index"
  devise_for :users
  resources :items do
    member do
      patch :complete
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  enum status: { using: 0, recommended: 1, completed: 2 }

  def to_recommended
    if end_at.present? && end_at < Date.current && self.using?
      self.update(status: :recommended)
    end
  end

  def to_using
    if  end_at.present? && end_at >= Date.current && self.recommended?
      self.update(status: :using) # 交換推奨から使用中に（条件に応じて）
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name line_user_id])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name line_user_id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :check_items_status
  def index
    @items = current_user.items.order(:id)
  end

  def new
    @item = Item.new
  end

  def create
    item = current_user.items.new(item_params)
    item.save!
    redirect_to items_path
  end


  def show
    @item = current_user.items.find(params[:id])
  end

  def edit
    @item = current_user.items.find(params[:id])
  end

  def update
    @item = current_user.items.find(params[:id])
    if @item.update(item_params)
      @item.to_using# アイテムのステータスをチェックして必要に応じて更新
      flash[:success] = "#{@item.name}が使用中に更新されました。"
      redirect_to items_path
    else
      render :edit
    end
  end


  def destroy
    item = current_user.items.find(params[:id])
    item.destroy
    flash[:success] = "#{item.name}を削除しました。"
    redirect_to items_path 
  end

  def complete
    @item = current_user.items.find(params[:id])
    @item.completed!
    flash[:success] = "#{@item.name}交換完了に更新されました。"
    redirect_to items_path 
  end



  private

  def item_params
    params.require(:item).permit(:name, :reminder_days_before_end, :start_at, :end_at)
  end

  def check_items_status
    current_user.items.each do |item|
      item.to_recommended
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_alert_class(type)
    case type.to_sym
    when :notice
      'alert-info'
    when :success
      'alert-success'
    when :error, :alert
      'alert-danger'
    else
      'alert-primary'
    end
  end
end

app/helpers/guides_helper.rb
# frozen_string_literal: true

module GuidesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/guides/how_to_use.html.erb
<h1>How to Use</h1>
<p>アプリの使い方の説明のページ</p>

<% if user_signed_in? %>
  <%= link_to 'Logout', destroy_user_session_path,  data: { turbo_method: :delete } %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/items/_items_table.html.erb
<!-- _items_table.html.erb -->
<table class="table">
  <thead>
    <tr>
      <th>アイテム名</th>
      <th>経過日数</th>
      <th>残り日数/超過日数</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% items.each do |item| %>
      <tr>
        <td><%= item.name%></td>
        <td><%= (Date.today - item.start_at).to_i %>日</td>
        <td>
          <% if item.end_at %>
            <% days = (item.end_at - Date.today).to_i %>
            <%= days >= 0 ? "#{days}日" : "#{days.abs}日超過" %>
          <% else %>
            N/A
          <% end %>
        </td>
        <td>
          <% if item.completed? %>
            <%= link_to '削除', item, method: :delete, data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }, class: "btn btn-small btn-danger" %>
          <% else %>
            <%= link_to '詳細', item_path(item), class: "btn btn-small btn-info" %>
            <%= link_to '編集', edit_item_path(item), class: "btn btn-small btn-secondary" %>
          <% if item.recommended? %>
            <%= link_to '交換完了', complete_item_path(item), data: { turbo_method: :patch }, class: "btn btn-small btn-success" %>
          <% end %>
            <%= link_to '削除', item, method: :delete, data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }, class: "btn btn-small btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/edit.html.erb
<%= form_with model: @item, local: true do |f| %>

  <div class="form-group">
    <%= f.label :name, "商品名" %>
    <%= f.text_field :name, class: "form-control", placeholder: "商品名を入力" %>
  </div>

  <div class="form-group">
      <%= f.label :reminder_days_before_end, "リマインド通知日" %>
      <%= f.number_field :reminder_days_before_end, class: "form-control", placeholder: "何日まえに通知を受けたいか" %>
  </div>

  <div class="form-group">
    <%= f.label :start_at, "開始日" %>
    <%= f.date_field :start_at, class: "form-control" %>
  </div>

  <div class="form-group">
      <%= f.label :end_at, "終了日" %>
      <%= f.date_field :end_at, class: "form-control" %>
  </div>
  

  <div class="actions">
      <%= f.submit "変更する", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/items/index.html.erb
<!-- タブナビゲーション -->
<ul class="nav nav-pills nav-fill" id="itemTabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="using-tab" data-bs-toggle="tab"  data-bs-target="#using" role="tab" aria-controls="using" aria-selected="true">使用中</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="recommended-tab" data-bs-toggle="tab" data-bs-target="#recommended" role="tab" aria-controls="recommended" aria-selected="false">交換推奨</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="completed-tab" data-bs-toggle="tab" data-bs-target="#completed" role="tab" aria-controls="completed" aria-selected="false">交換完了</a>
  </li>
</ul>

<!-- タブコンテンツ -->
<div class="tab-content" id="itemTabsContent">
  <!-- 使用中 -->
  <div class="tab-pane fade show active" id="using" role="tabpanel" aria-labelledby="using-tab">
    <%= render 'items_table', items: @items.using %>
  </div>

  <!-- 交換推奨 -->
  <div class="tab-pane fade" id="recommended" role="tabpanel" aria-labelledby="recommended-tab">
    <%= render 'items_table', items: @items.recommended %>
  </div>

  <!-- 交換完了 -->
  <div class="tab-pane fade" id="completed" role="tabpanel" aria-labelledby="completed-tab">
    <%= render 'items_table', items: @items.completed %>
  </div>
</div>

app/views/items/new.html.erb
<%= form_with model: @item, local: true do |f| %>

  <div class="form-group">
    <%= f.label :name, "商品名" %>
    <%= f.text_field :name, class: "form-control", placeholder: "商品名を入力" %>
  </div>

  <div class="form-group">
      <%= f.label :reminder_days_before_end, "リマインド通知日" %>
      <%= f.number_field :reminder_days_before_end, class: "form-control", placeholder: "何日まえに通知を受けたいか" %>
  </div>

  <div class="form-group">
    <%= f.label :start_at, "開始日" %>
    <%= f.date_field :start_at, class: "form-control" %>
  </div>

  <div class="form-group">
      <%= f.label :end_at, "終了日" %>
      <%= f.date_field :end_at, class: "form-control" %>
  </div>
  

  <div class="actions">
      <%= f.submit "登録する", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/items/show.html.erb
<div>
  <h1>アイテム詳細</h1>
  <div class="item-details">
    <p><strong>商品名:</strong> <%= @item.name %></p>
    <p><strong>リマインド通知日:</strong> <%= @item.reminder_days_before_end %>日前</p>
    <p><strong>開始日:</strong> <%= @item.start_at.strftime('%Y年%m月%d日') if @item.start_at %></p>
    <p><strong>終了日予定日:</strong> <%= @item.end_at.strftime('%Y年%m月%d日') if @item.end_at %></p>
  </div>

  <div>
    <%= link_to '編集', edit_item_path(@item), class: "btn btn-secondary" %>
    <%= link_to '一覧に戻る', items_path, class: "btn btn-light" %>
    <%= link_to '削除', @item,method: :delete, data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }, class: "btn btn-small btn-danger" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-light text-center text-lg-start">
  <div class="container p-4">
    <div class="row">
      <div class="col-lg-12">
        <div class="text-center py-3">
          <%= link_to "利用規約", "#", class: "text-dark me-4" %>
          <%= link_to "プライバシーポリシー", "#", class: "text-dark me-4" %>
          <%= link_to "お問い合わせ", "#", class: "text-dark" %>
        </div>
      </div>
    </div>
  </div>

  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2024 交換くん
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "交換くん", root_path, id: "logo", class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to "アイテム一覧", items_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "アイテム追加", new_item_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "通知設定", '#', class: "nav-link" %></li>
        <% else %>
          <li class="nav-item"><%= link_to "新規登録", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ItemTrack</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
</head>

<body style="display: flex; flex-direction: column; min-height: 100vh;">
  <%= render 'layouts/header' %>
  <% flash.each do |message_type, message| %>
    <div class="alert <%= bootstrap_alert_class(message_type) %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <div class="container" style="flex: 1;">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/top/index.html.erb
<h1>Top#index</h1>

<p>アプリの使い方の説明のページ</p>

<% if user_signed_in? %>
  <%= link_to 'Logout', destroy_user_session_path,  data: { turbo_method: :delete } %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>